[package]
name = 'fcl'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ['staticlib']

[dependencies]
extendr-api = { package = "extendr-api", version = "0.7.0" }
chrono = "0.4.26"

[dev-dependencies]
extendr-engine = { package = "extendr-engine", version = "0.7.0" }
